version: "3.7"
services:
  mongo:
    image: mongo:4.4.4
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: $env_passwd
    volumes:
      - ./datadir:/data/db
networks:
  default:
    name: flipped_default
