version: "3.7"
services:
  pinner:
    image: $env_image
    container_name: pinner
    restart: always
    environment:
      - url=http://ipfs1:5001
      - mqServer=$env_mqServer
networks:
  default:
    name: flipped_default
