version: "3.7"
services:
  gateway1:
    build:
      context: ../
      dockerfile: Dockerfile_gateway
    image: registry.cn-beijing.aliyuncs.com/lj110119p/js-gateway:v0.1
    container_name: gateway1
    restart: always
    ports:
      - 6001:6001
    environment:
      - url=http://192.168.0.72:5001
      - mongoUrl=mongodb://linden:123456@192.168.0.72:27017/flipped
      - mqServer=111.19.254.170:9876
    volumes: 
      - ./src:/opt/node/src
networks:
  default:
    name: flipped_default
