version: "3.7"
services:
  ipfs0:
    restart: always
    image: ipfs/go-ipfs:v0.8.0
    container_name: ipfs0
    ports:
      - 4000:4000
    volumes:
      - ~/ipfs0:/data/ipfs
  ipfs1:
    restart: always
    image: ipfs/go-ipfs:v0.8.0
    container_name: ipfs1
    ports:
      - 4001:4001
    volumes:
      - ~/ipfs1:/data/ipfs
  ipfs2:
    restart: always
    image: ipfs/go-ipfs:v0.8.0
    container_name: ipfs2
    ports:
      - 4002:4002
    volumes:
      - ~/ipfs2:/data/ipfs
networks:
  default:
    name: flipped_default
