apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 2g
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: ingress-dweb
  namespace: hz-ldy
spec:
  rules:
  - host: dweb.cipfs.cn
    http:
      paths:
      - backend:
          service:
            name: svc-ipfs0
            port:
              number: 8080
        path: /ipfs
        pathType: Prefix
      - backend:
          service:
            name: svc-ipfs0
            port:
              number: 5001
        path: /api/v0
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 2g
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: ingress-csg
  namespace: hz-ldy
spec:
  rules:
  - host: csg.cipfs.cn
    http:
      paths:
      - backend:
          service:
            name: svc-ipfs0
            port:
              number: 5001
        path: /api/v0
        pathType: Prefix
      - backend:
          service:
            name: svc-ipfs-s1
            port:
              number: 6001
        path: /poss/v1/linden
        pathType: Prefix
      - backend:
          service:
            name: svc-ipfs-s2
            port:
              number: 6001
        path: /poss/v1/testnet
        pathType: Prefix
      - backend:
          service:
            name: svc-ipfs-s3
            port:
              number: 6001
        path: /poss/v1/xoado
        pathType: Prefix
