version: "3.7"
services:
  nginx:
    restart: always
    image: nginx:mainline
    container_name: nginx
    volumes:
     - ./nginx/conf.d:/etc/nginx/conf.d
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
     - 80:80
     - 143:143
    environment:
     - TZ=Asia/Shanghai
  gateway1:
    build:
      context: js-gateway
      dockerfile: Dockerfile
    image: registry.cn-beijing.aliyuncs.com/lj110119p/js-gateway:v0.1
    container_name: gateway1
    restart: always
    ports:
      - 6001:6001
    environment:
      - url=http://192.168.0.51:5001
networks:
  default:
    name: flipped_default
